// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC6y5AUJQdaKcGVu8TNbynQBNv9F1aJX4',
    appId: '1:103810636758:web:8eb4fa6878801cc0cc6277',
    messagingSenderId: '103810636758',
    projectId: 'goa-hostel-app',
    authDomain: 'goa-hostel-app.firebaseapp.com',
    storageBucket: 'goa-hostel-app.firebasestorage.app',
    measurementId: 'G-CN8LT0W739',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2BbMud3kRCQx16TJatTGvs2CbBCR6788',
    appId: '1:103810636758:android:bb98335eb502fa2ecc6277',
    messagingSenderId: '103810636758',
    projectId: 'goa-hostel-app',
    storageBucket: 'goa-hostel-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBst5XCq_a9QKpWPM3nlelp2P5TE7sIM4Y',
    appId: '1:103810636758:ios:e2662241d39741fecc6277',
    messagingSenderId: '103810636758',
    projectId: 'goa-hostel-app',
    storageBucket: 'goa-hostel-app.firebasestorage.app',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBst5XCq_a9QKpWPM3nlelp2P5TE7sIM4Y',
    appId: '1:103810636758:ios:e2662241d39741fecc6277',
    messagingSenderId: '103810636758',
    projectId: 'goa-hostel-app',
    storageBucket: 'goa-hostel-app.firebasestorage.app',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC6y5AUJQdaKcGVu8TNbynQBNv9F1aJX4',
    appId: '1:103810636758:web:378c9c53515b7746cc6277',
    messagingSenderId: '103810636758',
    projectId: 'goa-hostel-app',
    authDomain: 'goa-hostel-app.firebaseapp.com',
    storageBucket: 'goa-hostel-app.firebasestorage.app',
    measurementId: 'G-1E2DEJ4DJH',
  );
}
