import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

// Firebase options (generated by FlutterFire CLI)
import 'firebase_options.dart';

// Services
import 'package:miniproject/services/auth_service.dart';

// Auth Screens
import 'package:miniproject/screens/auth/login_screen.dart';

// Dashboard + Features
import 'package:miniproject/screens/dashboard/dashboard_screen.dart';
import 'package:miniproject/screens/complaints/add_complaint.dart';
import 'package:miniproject/screens/complaints/complaint_list.dart';
import 'package:miniproject/screens/notices/notices_screen.dart';

// API Screens
import 'package:miniproject/screens/news/news_screen.dart';
import 'package:miniproject/screens/weather/weather_screen.dart';
import 'package:miniproject/screens/holidays/holidays_screen.dart';
import 'package:miniproject/screens/vip/vip_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthService()),
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Hostel App',

        // CLEAN THEME (NO BRIGHTNESS ERRORS)
        theme: ThemeData(
          useMaterial3: true,
          colorScheme: ColorScheme.fromSeed(
            seedColor: Colors.blue,
            brightness: Brightness.light,
          ),
        ),

        darkTheme: ThemeData(
          useMaterial3: true,
          colorScheme: ColorScheme.fromSeed(
            seedColor: Colors.blue,
            brightness: Brightness.dark,
          ),
        ),

        themeMode: ThemeMode.system,

        initialRoute: '/',

        routes: {
          '/': (context) => const LoginScreen(),
          '/dashboard': (context) => const DashboardScreen(),

          // Complaints
          '/addComplaint': (context) => const AddComplaintScreen(),
          '/complaintList': (context) => const ComplaintListScreen(),
          '/notices': (context) => const NoticesScreen(),

          // API screens
          '/news': (context) => const NewsScreen(),
          '/weather': (context) => const WeatherScreen(),
          '/holidays': (context) => const HolidaysScreen(),
          '/vip': (context) => const VipScreen(),

          // REMOVED — because file does NOT exist
          // '/profile': (context) => ProfileScreen(),
        },
      ),
    );
  }
}
